---
- name: Create Logstash configuration files.
  template:
    src: "logstash.yml.j2"
    dest: "/etc/logstash/logstash.yml"
    owner: logstash
    group: logstash
    mode: 0644
#  with_items:
#    - 01-beats-input.conf
#    - 30-elasticsearch-output.conf
  notify: restart logstash

# JVM options file
- name: Create Logstash JVM-Options configuration files.
  template:
    src: "jvm.options.j2"
    dest: "/etc/logstash/jvm.options"
    owner: logstash
    group: logstash
    mode: 0644

