---
- name: Create Logstash configuration files.
  template:
    src: "{{ item.name }}"
    dest: "{{ item.path }}"
#    mode: "{{ item.mode }}"
  with_items:
      - { name: 'logstash.yml.j2', path: '/etc/logstash/logstash.yml' }
      - { name: '02-beats-input.conf.j2', path: '/etc/logstash/conf.d/02-beats-input.conf' }
      - { name: '10-syslog-filter.conf.j2', path: '/etc/logstash/conf.d/10-syslog-filter.conf' }
      - { name: '30-elasticsearch-output.conf.j2', path: '/etc/logstash/conf.d/30-elasticsearch-output.conf' }
#  owner: logstash
#  group: logstash
#  mode: 0644
  notify: restart logstash

## JVM options file
#- name: Create Logstash JVM-Options configuration files.
#  template:
#    src: "jvm.options.j2"
#    dest: "/etc/logstash/jvm.options"
#    owner: logstash
#    group: logstash
#    mode: 0644

