---
- name: Dependent file for Centos6
  yum: name=libselinux-python state=installed
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '6'

- name: Add logstash repo
  template: src=logstash.repo.j2 dest=/etc/yum.repos.d/logstash.repo

- name: Install Logstash.
  yum: pkg=logstash state=installed
  notify:
   - restart logstash

