---
# tasks file for logstash

#- name: Include Java setup tasks
#  include: Java{{ ansible_os_family }}.yml


- name: Include OS Specific setup tasks
  include: logstash{{ ansible_os_family }}.yml

- include: config.yml

- name: Ensure Logstash is started and enabled on boot.
  service:
    name: logstash
    state: started
#    enabled: "{{ logstash_enabled_on_boot }}"
